version: 2.1
orbs:  
  nx: nrwl/nx@1.0.0
jobs:
  main:
    docker:
      - image: cimg/node:16.10
    environment:
      NX_CLOUD_DISTRIBUTED_EXECUTION: 'true'
    steps:
      - checkout
      - run: npm install
      - nx/set-shas
      - run: npx nx affected --base=$NX_BASE --target=build
      - run: npx nx affected --base=$NX_BASE --target=test
      - run: npx nx-cloud stop-all-agents
  pr:
    docker:
      - image: cimg/node:16.10
    environment:
      NX_CLOUD_DISTRIBUTED_EXECUTION: 'true'
    steps:
      - checkout
      - run: npm install
      - nx/set-shas
      - run: npx nx affected --base=$NX_BASE --target=build
      - run: npx nx affected --base=$NX_BASE --target=test
      - run: npx nx-cloud stop-all-agents
workflows:
  build:
    jobs:
      - main:
          filters:
            branches:
              only: main
      - pr:
          filters:
            branches:
              ignore: main